### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by favoyang** [Artees/Unity-Application-Version#1]
Hi @Artees,

Thanks for making this awesome UPM package. I'm the creator of the OpenUPM platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 200+ open-source UPM packages at the time of writing.

A kindly folk submitted your packages to the platform which brings me here.

I noticed you have a public registry running. If it makes sense for you, you can also make your packages available on the OpenUPM registry. It's a low friction way, just create GitHub releases (which create Git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

After your GitHub release, our build pipelines will detect the changes and build UPM packages in 5-10 minutes. Then you can visit your package at https://openupm.com/packages/games.artees.application-version/.

If the process makes sense, feel free to add Git tags for other your repositories. 
![image](https://user-images.githubusercontent.com/125390/81483323-f05eef00-926f-11ea-9115-82cb5b0a6468.png)

Even if you'd like to keep your own way, never mind, you can still get benefits from the [CLI](https://github.com/openupm/openupm-cli#openupm-cli)
```
openupm add games.artees.application-version --registry=https://upm.artees.games:4873
```

**Comment by Artees** [comment]
Thanks, I'll look into it when I have some free time.

**Comment by favoyang** [comment]
Nice, it works.

![image](https://user-images.githubusercontent.com/125390/81946513-0551ce80-9632-11ea-831c-feaf0cd38d0c.png)
